-- MySQL Script generated by MySQL Workbench
-- Wed Jun  7 16:22:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_awsimulate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_awsimulate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_awsimulate` DEFAULT CHARACTER SET utf8 ;
USE `db_awsimulate` ;

-- -----------------------------------------------------
-- Table `db_awsimulate`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_awsimulate`.`Person` ;

CREATE TABLE IF NOT EXISTS `db_awsimulate`.`Person` (
  `idPerson` INT NOT NULL,
  `namePerson` VARCHAR(45) NOT NULL,
  `emailPerson` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idPerson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_awsimulate`.`Exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_awsimulate`.`Exam` ;

CREATE TABLE IF NOT EXISTS `db_awsimulate`.`Exam` (
  `id` INT NOT NULL,
  `nameExam` VARCHAR(256) NOT NULL,
  `descriptionExam` VARCHAR(1000) NOT NULL,
  `versionExam` VARCHAR(45) NULL,
  `timeDuration` VARCHAR(45) NOT NULL,
  `quantityTotalQuestions` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_awsimulate`.`QuestionSubject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_awsimulate`.`QuestionSubject` ;

CREATE TABLE IF NOT EXISTS `db_awsimulate`.`QuestionSubject` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_awsimulate`.`QuestionType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_awsimulate`.`QuestionType` ;

CREATE TABLE IF NOT EXISTS `db_awsimulate`.`QuestionType` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `quantityChoose` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_awsimulate`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_awsimulate`.`Question` ;

CREATE TABLE IF NOT EXISTS `db_awsimulate`.`Question` (
  `id` INT NOT NULL,
  `descriptionQuestion` VARCHAR(1000) NOT NULL,
  `explicationQuestionResult` VARCHAR(1000) NOT NULL,
  `QuestionSubject_id` INT NOT NULL,
  `QuestionType_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Question_QuestionSubject1_idx` (`QuestionSubject_id` ASC) VISIBLE,
  INDEX `fk_Question_QuestionType1_idx` (`QuestionType_id` ASC) VISIBLE,
  CONSTRAINT `fk_Question_QuestionSubject1`
    FOREIGN KEY (`QuestionSubject_id`)
    REFERENCES `db_awsimulate`.`QuestionSubject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Question_QuestionType1`
    FOREIGN KEY (`QuestionType_id`)
    REFERENCES `db_awsimulate`.`QuestionType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_awsimulate`.`QuestionAlternative`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_awsimulate`.`QuestionAlternative` ;

CREATE TABLE IF NOT EXISTS `db_awsimulate`.`QuestionAlternative` (
  `idQuestionAlternative` INT NOT NULL,
  `Question_id` INT NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `rightAlternative` TINYINT NOT NULL,
  `explicationWhyResult` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`idQuestionAlternative`, `Question_id`),
  INDEX `fk_QuestionAlternative_Question1_idx` (`Question_id` ASC) VISIBLE,
  CONSTRAINT `fk_QuestionAlternative_Question1`
    FOREIGN KEY (`Question_id`)
    REFERENCES `db_awsimulate`.`Question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_awsimulate`.`SimulationExamQuestionAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_awsimulate`.`SimulationExamQuestionAssociation` ;

CREATE TABLE IF NOT EXISTS `db_awsimulate`.`SimulationExamQuestionAssociation` (
  `id` INT NOT NULL,
  `Exam_id` INT NOT NULL,
  `Question_id` INT NOT NULL,
  `nameSimulated` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `Exam_id`, `Question_id`),
  INDEX `fk_SimulationExamQuestionAssociation_Exam1_idx` (`Exam_id` ASC) VISIBLE,
  INDEX `fk_SimulationExamQuestionAssociation_Question1_idx` (`Question_id` ASC) VISIBLE,
  CONSTRAINT `fk_SimulationExamQuestionAssociation_Exam1`
    FOREIGN KEY (`Exam_id`)
    REFERENCES `db_awsimulate`.`Exam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SimulationExamQuestionAssociation_Question1`
    FOREIGN KEY (`Question_id`)
    REFERENCES `db_awsimulate`.`Question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_awsimulate`.`ExamQuestionAssociation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_awsimulate`.`ExamQuestionAssociation` ;

CREATE TABLE IF NOT EXISTS `db_awsimulate`.`ExamQuestionAssociation` (
  `Exam_id` INT NOT NULL,
  `Question_id` INT NOT NULL,
  PRIMARY KEY (`Exam_id`, `Question_id`),
  INDEX `fk_Exam_has_Question_Question1_idx` (`Question_id` ASC) VISIBLE,
  INDEX `fk_Exam_has_Question_Exam1_idx` (`Exam_id` ASC) VISIBLE,
  CONSTRAINT `fk_Exam_has_Question_Exam1`
    FOREIGN KEY (`Exam_id`)
    REFERENCES `db_awsimulate`.`Exam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exam_has_Question_Question1`
    FOREIGN KEY (`Question_id`)
    REFERENCES `db_awsimulate`.`Question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_awsimulate`.`PracticeExamHistoric`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_awsimulate`.`PracticeExamHistoric` ;

CREATE TABLE IF NOT EXISTS `db_awsimulate`.`PracticeExamHistoric` (
  `id` INT NOT NULL,
  `Person_idPerson` INT NOT NULL,
  `SimulationExamQuestionAssociation_id` INT NOT NULL,
  `SimulationExamQuestionAssociation_Exam_id` INT NOT NULL,
  `datetimeGetStarted` DATETIME NOT NULL,
  `datetimeFinished` DATETIME NULL,
  `percentScore` DECIMAL(5,2) NULL,
  `timeSpent` VARCHAR(45) NULL,
  `numberCorrectQuestions` INT NULL,
  PRIMARY KEY (`id`, `Person_idPerson`, `SimulationExamQuestionAssociation_id`, `SimulationExamQuestionAssociation_Exam_id`, `datetimeGetStarted`),
  INDEX `fk_PracticeExamHistoric_Person1_idx` (`Person_idPerson` ASC) VISIBLE,
  INDEX `fk_PracticeExamHistoric_SimulationExamQuestionAssociation1_idx` (`SimulationExamQuestionAssociation_id` ASC, `SimulationExamQuestionAssociation_Exam_id` ASC) VISIBLE,
  CONSTRAINT `fk_PracticeExamHistoric_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `db_awsimulate`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PracticeExamHistoric_SimulationExamQuestionAssociation1`
    FOREIGN KEY (`SimulationExamQuestionAssociation_id` , `SimulationExamQuestionAssociation_Exam_id`)
    REFERENCES `db_awsimulate`.`SimulationExamQuestionAssociation` (`id` , `Exam_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_awsimulate`.`QuestionAlternativeSelected`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_awsimulate`.`QuestionAlternativeSelected` ;

CREATE TABLE IF NOT EXISTS `db_awsimulate`.`QuestionAlternativeSelected` (
  `PracticeExamHistoric_id` INT NOT NULL,
  `PracticeExamHistoric_Person_idPerson` INT NOT NULL,
  `PracticeExamHistoric_SimulationExamQuestionAssociation_id` INT NOT NULL,
  `PracticeExamHistoric_SimulationExamQuestionAssociation_Exam_id` INT NOT NULL,
  `SimulationExamQuestionAssociation_Question_id` INT NOT NULL,
  INDEX `fk_QuestionAlternativeSelected_PracticeExamHistoric1_idx` (`PracticeExamHistoric_id` ASC, `PracticeExamHistoric_Person_idPerson` ASC, `PracticeExamHistoric_SimulationExamQuestionAssociation_id` ASC, `PracticeExamHistoric_SimulationExamQuestionAssociation_Exam_id` ASC) VISIBLE,
  INDEX `fk_QuestionAlternativeSelected_SimulationExamQuestionAssoci_idx` (`SimulationExamQuestionAssociation_Question_id` ASC) VISIBLE,
  PRIMARY KEY (`PracticeExamHistoric_id`, `PracticeExamHistoric_Person_idPerson`, `PracticeExamHistoric_SimulationExamQuestionAssociation_id`, `PracticeExamHistoric_SimulationExamQuestionAssociation_Exam_id`, `SimulationExamQuestionAssociation_Question_id`),
  CONSTRAINT `fk_QuestionAlternativeSelected_PracticeExamHistoric1`
    FOREIGN KEY (`PracticeExamHistoric_id` , `PracticeExamHistoric_Person_idPerson` , `PracticeExamHistoric_SimulationExamQuestionAssociation_id` , `PracticeExamHistoric_SimulationExamQuestionAssociation_Exam_id`)
    REFERENCES `db_awsimulate`.`PracticeExamHistoric` (`id` , `Person_idPerson` , `SimulationExamQuestionAssociation_id` , `SimulationExamQuestionAssociation_Exam_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QuestionAlternativeSelected_SimulationExamQuestionAssociat1`
    FOREIGN KEY (`SimulationExamQuestionAssociation_Question_id`)
    REFERENCES `db_awsimulate`.`SimulationExamQuestionAssociation` (`Question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
